

library(shiny)

ui <- fluidPage(
  
  titlePanel("A/B INsight"),
  
  tabsetPanel(
    tabPanel("KPI's", value = "kpis",
             h3("KPI's"),
             h4("This tab provides a comprehensive view of the key performance indicators (KPI's) of your A/B test."),
             selectInput("view", "Select View:",
                         c("Daily", 
                           "Monthly", 
                           "Date Range")),
             selectInput("variable", "Select Variable:",
                         c("Spend (USD)", 
                           "Impressions", 
                           "Reach",
                           "Clicks", 
                           "Searches", 
                           "View Content",
                           "Add to Cart", 
                           "Purchase")),
             h4("Cart Abandonment Rate"),
             h4("Cost per Action"),
             h4("Engagement Rate"),
             h4("Funnel")),
    tabPanel("Overview", value = "overview",
             h3("Overview"),
             h4("This tab provides a high-level view of the counts of the selected variable for the selected time period."),
             selectInput("view", "Select View:",
                         c("Daily", 
                           "Monthly", 
                           "Date Range")),
             selectInput("variable", "Select Variable:",
                         c("Spend (USD)", "Impressions", "Reach",
                           "Clicks", "Searches", "View Content",
                           "Add to Cart", "Purchase")),
             actionButton("run_analysis", "Run Analysis")),
    tabPanel("Cost per Action", value = "costs",
             h3("Cost per Action"),
             h4("This tab provides a view of the cost per action for the selected variable."),
             selectInput("cost_variable", "Select Variable:",
                         c("Cost per Impression", 
                           "Cost per Reach", 
                           "Cost per Click", 
                           "Cost per Search", 
                           "Cost per View Content", 
                           "Cost per Add to Cart", 
                           "Cost per Purchase")),
             actionButton("run_analysis", "Run Analysis")),
    tabPanel("Conversion Rate", value = "conversions",
             h3("Conversion Rate"),
             h4("This tab provides a view of the conversion rate for the selected variable."),
             selectInput("conversion_variable", "Select Variable:",
                         c("Purchase Conversion Rate", 
                           "Add to Cart Conversion Rate")),
             actionButton("run_analysis", "Run Analysis")),
    tabPanel("Engagement", value = "engagement",
             h3("Engagement"),
             h4("This tab provides a view of the engagement rate for the selected variable."),
             selectInput("engagement_variable", "Select Variable:",
                         c("Content Engagement Rate", 
                           "Product Engagement Rate", 
                           "Add to Cart Engagement Rate", 
                           "Purchase Engagement Rate")),
             actionButton("run_analysis", "Run Analysis")),
    tabPanel("Outliers", value = "outliers",
             h3("Outliers"),
             h4("Displays dates of outliers for the selected variable"),
             selectInput("outlier_variable", "Select Variable:",
                         c("Spend (USD)", "Impressions", "Reach",
                           "Clicks", "Searches", "View Content",
                           "Add to Cart", "Purchase")),
             actionButton("run_analysis", "Run Analysis")),
    tabPanel("About this App", value = "about_app",
             h3("About this App"),
             verbatimTextOutput("app_info")),
    tabPanel("About the Coder", value = "about_coder",
             h3("About the Coder"),
             verbatimTextOutput("coder_info"))
    ),
    
    mainPanel(
      plotOutput("plot"),
      actionButton("print_report", "Print Report"),
      actionButton("email_pdf", "Email PDF"),
      actionButton("email_page_link", "Email Page Link"),
      actionButton("copy_link", "Copy Link")
    )
  )


